[tool.poetry]
name = "cuia"
version = "0.1.0"
description = "ğŸ§“ğŸ¾ğŸ–¥ï¸ An old lady made a text-based app."
authors = ["Felipe S. S. Schneider <schneider.felipe@posgrad.ufsc.br>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^21.10b0", allow-prereleases = true}
pydocstyle = "^6.1.1"
mypy = "^0.910"
isort = "^5.9.3"
flake8 = "^4.0.1"
bandit = "^1.7.0"
requests = "^2.26.0"
types-requests = "^2.25.11"
pylint = "^2.11.1"
snakeviz = "^2.1.1"
pdoc = "^8.0.1"
pyfiglet = "^0.8.post1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
